name: Merge Labeler
on:
  pull_request:
    types: [closed]
jobs:
  remove-label:
    runs-on: ubuntu-latest
    steps:
      - uses: buildsville/add-remove-label@v1
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          label: review me
          type: remove

  merge-labeler:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/merge-labeler.yml
